import { HANDLE_IDS, branchHandle } from '@activepieces/shared';
import { Handle, Position } from '@xyflow/react';
import React from 'react';

const handleBaseStyle: React.CSSProperties = {
  width: 10,
  height: 10,
  borderRadius: '50%',
  backgroundColor: '#94a3b8',
  border: '2px solid #fff',
};

/**
 * Input handle rendered at the top-center of the node.
 * Used by all non-trigger nodes.
 * ID matches HANDLE_IDS.INPUT from connection-rules.ts.
 */
export const GraphInputHandle: React.FC = () => (
  <Handle
    type="target"
    position={Position.Top}
    id={HANDLE_IDS.INPUT}
    style={handleBaseStyle}
  />
);

/**
 * Output handle rendered at the bottom-center of the node.
 * Used by all nodes (triggers and actions).
 * ID matches HANDLE_IDS.OUTPUT from connection-rules.ts.
 * Maps to nextAction in the linked-list model.
 */
export const GraphOutputHandle: React.FC = () => (
  <Handle
    type="source"
    position={Position.Bottom}
    id={HANDLE_IDS.OUTPUT}
    style={handleBaseStyle}
  />
);

/**
 * Loop output handle rendered on the right side of loop nodes.
 * ID matches HANDLE_IDS.LOOP_OUTPUT from connection-rules.ts.
 * Maps to firstLoopAction in the linked-list model.
 */
export const GraphLoopOutputHandle: React.FC = () => (
  <Handle
    type="source"
    position={Position.Right}
    id={HANDLE_IDS.LOOP_OUTPUT}
    style={{
      ...handleBaseStyle,
      backgroundColor: '#8b5cf6',
    }}
  />
);

/**
 * Branch handle rendered on the right side of router nodes.
 * ID generated by branchHandle(index) from connection-rules.ts.
 * Maps to children[index] in the linked-list model.
 *
 * @param index - zero-based branch index
 */
export const GraphBranchHandle: React.FC<{ index: number }> = ({ index }) => (
  <Handle
    type="source"
    position={Position.Right}
    id={branchHandle(index)}
    style={{
      ...handleBaseStyle,
      backgroundColor: '#f59e0b',
      top: `${50 + index * 20}%`,
    }}
  />
);
